### ISSUE TITLE
This repository should live underneath https://github.com/NixOS/

### ISSUE THREAD

**Issue by peti** [NixOS/nixos-hardware#11] opened 2016-04-20 12:16 UTC
It's very hard for new users to discovers this repository. Also, it belongs into the organization from a structural point of view.

**Comment by ehmry** [comment] 2016-04-20 13:21
@peti I'm all for it but the problem is I don't have the rights to move it into nixos on my own.

**Comment by ehmry** [comment] 2016-04-20 13:23
If someone creates a new repo at NixOS I can remove this one.

**Comment by peti** [comment] 2016-04-20 13:58
Just contact Eelco or Rob in IRC or by email and ask  them to create a repo for you. That shouldn't be a problem?

**Comment by ehmry** [comment] 2016-04-20 14:47
@edolstra @rbvermaa how about it?

**Comment by Ericson2314** [comment] 2016-04-20 18:00
@ehmy Last I checked I thought anybody could transfer a repo, just need somebody in the org to accept transfer?

If that's not the case better to give an org member admin rights to this repo, so they can transfer it. That way fork graph and issue will be preserved.

**Comment by ehmry** [comment] 2016-04-20 18:03
Thats how it should work, but alas, not how it does work.

**Comment by Ericson2314** [comment] 2016-04-20 18:07
Then my plan B?

**Comment by ehmry** [comment] 2016-04-20 18:35
I can't give admin rights to a repo, but I could probably transfer the repo to a nixos admin who could then pass it on the the nixos org.

**Comment by Ericson2314** [comment] 2016-04-20 18:37
That will do. Thanks!

**Comment by edolstra** [comment] 2016-04-21 09:56
Hm, we should probably define the scope/purpose of this repository a bit. It appears to be two things:

* A repository of hardware-related modules (with some user configurations thrown in, e.g. https://github.com/ehmry/nixos-hardware/blob/master/inversepath/usbarmory/configuration.nix). When should hardware modules go into `<nixpkgs/nixos/modules>` and when into this repository? Putting hardware modules in a separate repository creates a version management problem, e.g. when a module refers to options/packages introduced in a particular NixOS revision. Also, it's hard for `nixos-generate-config` to refer to modules not in the Nixpkgs repo, while ideally hardware quirks would be detected automatically by `nixos-generate-config`.

* A wiki. But do we want to have a separate wiki *only* for model-specific hardware issues?

**Comment by peti** [comment] 2016-04-21 12:18
My understanding was that this repository is a loose collection of code snippets that people can cut&paste and/or import into their `configuration.nix`. Arguably, this is Wiki'ish in nature, only it's tracked in a proper Git repository.

**Comment by ehmry** [comment] 2016-04-25 17:46
Having detectable hardware modules in ``nixpkgs/nixos/modules`` would be preferable, but I think there is there is a grey area for quality assurance. That seems to make this a wiki of user snippets, but what is the plan for the https://nixos.org/wiki ? @garbas any thought?

**Comment by Ericson2314** [comment] 2016-04-25 17:55
Yeah, if this really takes off, we can
1. Merge it in nixpkgs (remember `git subtree` can help preserve history)
2. Integrate the Nixos modules with existing hardware detection. (As far as QA is concerned, we'd could decide whether to use them by default---boils down to a kind of parametricity property.)
3. Move the wikis with the rest of our documentation, also the destination of the old wiki's info last I checked.

But given that this is still an experiment, and sticking even more things in nixpkgs would require some sort of community consensus, I think moving this repo is the proper first step for now.

**Comment by edolstra** [comment] 2016-04-25 20:17
Yeah I agree. I've created https://github.com/NixOS/nixos-hardware, which should be writable to all Nixpkgs committers.

**Comment by Ericson2314** [comment] 2016-04-25 20:25
@edolstra did you see my earlier comments about moving the repository so github fork information and other metadata is preserved?

**Comment by edolstra** [comment] 2016-04-26 08:49
Sorry, didn't see that. So what should I do to move the repo?

**Comment by ehmry** [comment] 2016-04-26 08:50
Meh, I already pushed to the new one.

**Comment by ehmry** [comment] 2016-04-26 08:51
@edolstra I transfered the repo to you, so you should be able to hand it off to the Nixos org.

**Comment by edolstra** [comment] 2016-04-26 08:57
Okay, done. Thanks!

**Closed by edolstra** 2016-04-26 08:57 UTC

**Comment by Ericson2314** [comment] 2016-04-26 14:44
Excellent; thank you all!

**Comment by garbas** [comment] 2016-04-28 11:25
thank you! this reminds me i have to put in my lenovo x250 configs there :)
