### ISSUE TITLE
surface range camera support

### ISSUE THREAD

**Issue by phpcitizen** [NixOS/nixos-hardware#483] opened 2022-10-16 01:02 UTC
It seems like Microsoft Surface Camera Support is not working. Surface Pro 5 (2017)

[Linux Surface Camera Support](https://github.com/linux-surface/linux-surface/wiki/Camera-Support)
I don't know how to apply those for NixOS
Installed libcamera from nix packages, did not make any difference.

If anyone knows a workaround please let me know.

**Comment by Mic92** [comment] 2023-02-20 21:10
Duplicate of https://github.com/NixOS/nixos-hardware/issues/523#issuecomment-1404714880 I think

**Closed by Mic92** 2023-02-20 21:10 UTC
