### ISSUE TITLE
Is disabling scatter/gather on AMD necessary in newer kernels?

### ISSUE THREAD

**Issue by nyabinary** [NixOS/nixos-hardware#918] opened 2024-04-19 15:14 UTC
Currently, we just disable scatter and gather on any kernel version newer than 6.2, but is this necessary or has the issue causing it to be disabled in the first place been resolved?
https://github.com/NixOS/nixos-hardware/blob/5d48925b815fd202781bfae8fb6f45c07112fdb2/common/cpu/amd/raphael/igpu.nix#L16

**Comment by JohnRTitor** [comment] 2024-06-15 02:04
Looks like it was added in https://github.com/NixOS/nixos-hardware/pull/598

I don't think that's relevant now on 6.6 LTS or later. Can you double check though, before I send a PR?

**Comment by Mic92** [comment] 2024-06-15 12:12
I am already closing the pull request here, because the causing code will be soon in nixpkgs.

**Comment by JohnRTitor** [comment] 2024-06-15 12:20
@Mic92 could you link the PR? If you are referring to #319865, it's not related to this.

**Comment by Mic92** [comment] 2024-06-15 12:44
I thought it was.

**Comment by JohnRTitor** [comment] 2024-06-15 13:28
Looks like the issue is no longer observed in kernel 6.6+. Thus it is not necessary to set this kernel param. #980 should fix it.

**Closed** 2024-06-15 13:46 UTC
